apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: selenium-grid-operator-system
namePrefix: selenium-grid-operator-

patchesStrategicMerge:
- namespace_scope_patch.yaml
resources:
- ../crd
- ../rbac/namespaced
- ../manager
