# permissions for end users to view seleniumgrids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seleniumgrid-viewer-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - seleniumgrids
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - seleniumgrids/status
  verbs:
  - get
