# permissions for end users to edit seleniumgrids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seleniumgrid-editor-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - seleniumgrids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - seleniumgrids/status
  verbs:
  - get
