---
- fail:
    msg: "Must set expose.uri when using Ingress as expose.kind and when expose.ssl is True"
  when:
    - _selenium_ssl
    - _selenium_expose_method == 'Ingress'
    - _selenium_expose_uri is empty

# tasks file for Selenium Grid
- name: Set OpenShift Objects for Selenium Grid to {{ _selenium_state }}
  k8s:
    state: "{{ _selenium_state }}"
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - service-account.yml.j2
  - service.yml.j2
  - deployment.selenium-hub.yml.j2
  # - deployment.selenium-node-chrome-debug.yml.j2
  - deployment.selenium-node-chrome.yml.j2
  # - deployment.selenium-node-firefox-debug.yml.j2
  - deployment.selenium-node-firefox.yml.j2

- name: Set Selenium Grid {{ _selenium_expose_method }} to {{ _selenium_state }}
  when: _selenium_expose_method != 'None'
  k8s:
    state: "{{ _selenium_state }}"
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', _selenium_expose_method + '.yml.j2') | from_yaml }}"

- name: Wait until application is available
  when:
    - _selenium_state == "present"
    - _selenium_wait_for_init|bool
  k8s_facts:
    api_version: apps/v1
    kind: Deployment
    name: "{{ _selenium_name }}-selenium-hub"
    namespace: "{{ _selenium_namespace }}"
  register: r_deployment
  until:
  - r_deployment.resources[0].status.availableReplicas is defined
  - r_deployment.resources[0].status.availableReplicas == 1
  retries: 50
  delay: 10
  ignore_errors: yes
